[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1r4zKKfsEPS51n7nH0nc6EQd1LRAL06vmoS-Y5cS0IiY/edit?gid=0#gid=0"

type = "service_account"
project_id = "mimetic-sweep-322719"
private_key_id = "1c455a049c9b8905aa412ea06fa3d30ced31a271"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDRy+FtgO4scGM/
06ou2KJg3/qvhSN4Hig1JGBfmpHSRs2ha5sA1tVdio979QEZYwQxx0pMV+4ooT3d
Qy4WfJZ+291/vV4Pyg9w2+1s5bu0nGKRJqTgVDPITyX0jPepeEwsxhnwaUri2aLx
ObdpVuLz0gFNFk0KFBQCUka74oa1OYVZyp8CUScYv8dZvSP6keJTIrHxzCeJFf0m
NTM+3/U54SkbdvwQawAIwjVJY4dKG4DoAbZqk/Rjxi1/4LvMqxWKO39h5IVmFS0x
8BQ4024mk3L0Vj34U/q5VmWHPzdNoaVJPUUqowoHmq5B//L+Ial8zvkl/AnHxAwX
t7Xez1R9AgMBAAECggEAG7bcsTwKeplgKxLZlPWuQbDk62HhpSEKu7Zx+r8vC0Gq
MWxHHi3DIufGe6AKhKGFcNP8Vyh4gCqIwx14TaUotlpyIMlRzzEoqAaNj0ir6riL
9tPNjQriilAWWf9zShJnsbR7wbwPFfedJFO1DHfbZE02Oco75Bxx5jqbOH+8vty8
cGRwHHfkGw7sgrDzrUpEgb4haqvBC5FPcDw8wZsgDTi0L/E7B/ih0veG2xC+1962
I6pHbiTlkB+bI4l9VlbmzUWozDmeVEEJ02YZgbVe4YtAKApca0ljmxxZg3V+dkyD
mItbtGYefmxWSRLRn0VrNtqcLoryAf+bR+nbpkhTOwKBgQD8zXPJRh0SgXr9nHkG
/vICNdPHVjngFetezeBsg5mMcVpUYyRA6Jv9m2fL6VA579exWcnJNxQS1KmLgRny
lLvCPmtTwHV3wft3cEy+IfskNVW8hiuFepkXDld5fv8nP8WmWBl5KrFeqV91wMMC
jWnqiuLmcjGrUKRavuCci+61AwKBgQDUcy3SUphVncIlm+1jmmLVsNtxIFWgC8uB
3je9My8PMQiKkc+eoShy/whrhDEcdKO0hIWiDUzw639bv4IdL9NgtzYrTwpK9Set
6FFErad3cBsrU2BNXtIPdfLxTSH6U5XjnidaSCEDg6RdUmG32x+NBfIxZCQCF1RK
AA2Qg+PYfwKBgQCQZt77mmQi3PkfApETUO92Gb8VvwgiGwMuTRUjhuxfj6QUTek4
dmYcL/fTPztHTNv8/xfHKwH5W6ZY/G6Q5Sp24ua1mVrABHsal3gOpyRoY1rM7CrR
/NyTkeqfiM5AYioJQYuTbbKRKthPT8NUouhcQ+cl0RbUD6VB/IQah8fbdwKBgHRh
/JIhiS4t1DPCLdPIuagS0MQyUHXywDOOxr4xEfCijelLY4+k/YGx0K0Fp9nM0/mK
N6LE4oeAmy5pxR+0GXn8JAKptBvIHUqZ4BtdfkZh9aBQdossDKtHlCU4egqmS5B8
DVbZ+KvyK9Kr1Lhho/EfdsQz9b3nhddcHBI1DlaFAoGBAKDlALexPQxMW9OM9APq
JD0XAKq7B7W1n0lK0Y+nwDWgPR/kLISuhSQO8doOy2BjlPeHCVC8+LC7UGftCwsV
dnrDYzF2Evce5pj+sFGOcDpb8cZPCuIliw16L3h+xoZ3onCzaAp/AeFF0IIY2wMI
A8gd8HT/MEwB/PxEV0NV0hUd
-----END PRIVATE KEY-----"""
client_email = "service-acc-2025@mimetic-sweep-322719.iam.gserviceaccount.com"
client_id = "107728514311507667229"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-acc-2025%40mimetic-sweep-322719.iam.gserviceaccount.com"
