name: Deploy Streamlit App

env:
  SECRET_JSON: ${{ secrets.SECRET_JSON }}

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Create secrets.json from GitHub Secrets
        run: echo '${{ secrets.SECRET_JSON }}' > secrets.json

      - name: Show that file exists (optional debug)
        run: cat secrets.json

      - name: Install Streamlit
        run: pip install streamlit

      - name: Deploy or Run App (example)
        run: Meeting3_Discussion.py
          # Use the secrets.json file however needed
          # For example, run your Streamlit app locally for testing
          
